### ISSUE TITLE
Does CEnshine work with OpenSauce?

### ISSUE THREAD

**Issue by N8endo** [Sledmine/censhine#1]
I tried it with SPV3 and stock CE with OpenSauce installed.  In both installs, I'm using Chimera 1.0 version 50 which is the last version compatible with OpenSauce.  I got CEnshine working on CE after disabling OpenSauce.  Are CEnshine and OpenSauce completely incompatible, or can they somehow be made to work together?
Thanks!

**Comment by Sledmine** [comment]
Sorry for replying TOO late, It does not work with OpenSauce.

Basically OpenSauce has it's own set of shaders based on the original broken ones from Gearbox, they are just an extension of those shaders.

OpenSauce overrided the way the game loads shaders so it forces it to load a different set of shaders "EffectCollection_ps_2_0_b.enc" (or something like that), these shaders have the normal stock behaviour of the Gearbox shaders and the extensions for OpenSauce shaders.

So even if you replace the shaders that OpenSauce is looking for you will have probably a crash or black shaders being rendered because OpenSauce shaders don't exist anymore in the shaders file, so in theory OpenSauce could be compatible by recompiling CEnshine shaders code + OpenSauce shaders code to be able to achieve this.

But I consider this kind of difficult and also OpenSauce is barely used these days so... it is doable but it will require some effort.
